/*
 * Project: NOUB SPORTS ECOSYSTEM
 * Filename: js/controllers/arenaCtrl.js
 * Version: Noub Sports_beta 0.0.2 (PRESS ENGINE)
 * Status: Production Ready
 * 
 * ARCHITECTURAL UPDATES:
 * 1. Press Integration: Renders dynamic headlines generated by NewsEngine via match_data.
 * 2. Data Payload: Passes Team Names to Service during submission for text generation.
 * 3. Interactive Feed: Match cards are clickable to reveal the full "Match Report".
 */

import { MatchService } from '../services/matchService.js';
import { TeamService } from '../services/teamService.js';
import { state } from '../core/state.js';
import { Helpers } from '../utils/helpers.js';
import { SoundManager } from '../utils/soundManager.js';

export class ArenaController {
    
    constructor() {
        this.matchService = new MatchService();
        this.teamService = new TeamService();
        this.viewContainer = document.getElementById('view-arena');
        
        // Internal Cache
        this.myTeamData = null;
        this.roster = [];
    }

    /**
     * Main Initialization
     */
    async init() {
        console.log("🏟️ ArenaController: Init (Press Edition)...");
        
        const currentUser = state.getUser();
        if (!currentUser) {
            this.viewContainer.innerHTML = `<div class="error-state">يجب تسجيل الدخول.</div>`;
            return;
        }

        this.viewContainer.innerHTML = '<div class="loader-center"><div class="loader-bar"></div></div>';

        try {
            // Fetch Role
            const myTeam = await this.teamService.getMyTeam(currentUser.id);
            const isCaptain = myTeam?.my_role === 'CAPTAIN';

            if (isCaptain) {
                this.myTeamData = myTeam;
                this.roster = await this.teamService.getTeamRoster(myTeam.id);
            }

            this.renderLayout(isCaptain);
            await this.loadLiveFeed(currentUser.zoneId);

        } catch (err) {
            console.error("Arena Error:", err);
            this.viewContainer.innerHTML = `<div class="error-state">خطأ في التحميل.</div>`;
        }
    }

    /**
     * Renders Tabs Layout
     */
    renderLayout(isCaptain) {
        this.viewContainer.innerHTML = `
            <div class="arena-container fade-in">
                <div class="arena-tabs">
                    <button class="tab-btn active" data-tab="feed">
                        <i class="fa-solid fa-newspaper"></i> الأخبار
                    </button>
                    ${isCaptain ? `
                        <button class="tab-btn" data-tab="create">
                            <i class="fa-solid fa-pen-to-square"></i> تسجيل
                        </button>
                    ` : ''}
                </div>
                <div id="arena-content"></div>
            </div>
        `;

        this.viewContainer.querySelectorAll('.tab-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                SoundManager.play('click');
                this.viewContainer.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                e.target.classList.add('active');

                const tab = e.target.dataset.tab;
                if (tab === 'feed') this.loadLiveFeed(state.getUser().zoneId);
                if (tab === 'create') this.renderCreateForm();
            });
        });
    }

    /**
     * TAB 1: Live Feed with Press Headlines
     */
    async loadLiveFeed(zoneId) {
        const container = document.getElementById('arena-content');
        container.innerHTML = '<div class="loader-bar" style="margin:20px auto"></div>';
        
        try {
            const matches = await this.matchService.getLiveFeed(zoneId);
            
            if (!matches.length) { 
                container.innerHTML = `
                    <div class="empty-state">
                        <i class="fa-solid fa-wind" style="font-size:3rem; margin-bottom:10px; color:#555;"></i>
                        <p>لا توجد مباريات (أو أخبار) حالياً.</p>
                    </div>`; 
                return; 
            }

            container.innerHTML = matches.map(m => {
                // Extract Press Data
                const headline = m.match_data?.headline || "مباراة قوية في المنطقة";
                const isConfirmed = m.status === 'CONFIRMED';
                const date = Helpers.formatDate(new Date(m.played_at));

                // Safe encode for modal
                const matchSafe = encodeURIComponent(JSON.stringify(m));

                return `
                <div class="match-card" onclick="window.openMatchDetails('${matchSafe}')" style="cursor:pointer;">
                    
                    <!-- Press Headline Banner -->
                    <div class="match-headline" style="padding-bottom:10px; margin-bottom:10px; border-bottom:1px solid rgba(255,255,255,0.05);">
                        <span style="font-size:0.85rem; color:var(--gold-main); font-weight:bold; line-height:1.4; display:block;">
                            ${isConfirmed ? headline : '🔴 مباراة جارية الآن...'}
                        </span>
                        <div style="font-size:0.65rem; color:var(--text-muted); display:flex; justify-content:space-between; margin-top:5px;">
                            <span>${date}</span>
                            <span>${m.venue?.name}</span>
                        </div>
                    </div>

                    <div class="scoreboard">
                        <div class="sb-team">
                            <div class="sb-logo" style="background:${m.team_a?.logo_dna?.primary || '#333'}"></div>
                            <span>${m.team_a?.name}</span>
                        </div>
                        <div class="sb-score">
                            ${m.score_a} - ${m.score_b}
                        </div>
                        <div class="sb-team">
                            <div class="sb-logo" style="background:${m.team_b?.logo_dna?.primary || '#333'}"></div>
                            <span>${m.team_b?.name}</span>
                        </div>
                    </div>
                    
                    ${isConfirmed ? 
                        `<div class="match-status status-confirmed">خبر رسمي</div>` : 
                        `<div class="match-status status-pending">في انتظار التوثيق</div>`
                    }
                </div>`;
            }).join('');

            // Bind Global Click Handler for Details (attached to window for innerHTML simplicity)
            window.openMatchDetails = (dataStr) => {
                const match = JSON.parse(decodeURIComponent(dataStr));
                this.showMatchReportModal(match);
            };

        } catch (e) {
            console.error(e);
            container.innerHTML = '<p class="error-text">فشل تحميل الأخبار.</p>';
        }
    }

    /**
     * Shows the "Match Report" Modal (The Article)
     */
    showMatchReportModal(match) {
        SoundManager.play('click');
        const modalId = 'modal-match-report';
        
        if (!document.getElementById(modalId)) {
            document.body.insertAdjacentHTML('beforeend', `
                <div id="${modalId}" class="modal-overlay hidden">
                    <div class="modal-box">
                        <div class="modal-header"><h3>تقرير المباراة</h3><button class="close-btn" onclick="document.getElementById('${modalId}').classList.add('hidden')">&times;</button></div>
                        <div id="match-report-content"></div>
                    </div>
                </div>`);
        }

        const modal = document.getElementById(modalId);
        modal.classList.remove('hidden');
        const content = document.getElementById('match-report-content');

        const bodyText = match.match_data?.body || "لا توجد تفاصيل إضافية.";

        content.innerHTML = `
            <div style="text-align:center; margin-bottom:20px;">
                <h2 style="color:var(--gold-main); font-family:var(--font-sport); margin-bottom:10px;">
                    ${match.score_a} - ${match.score_b}
                </h2>
                <div style="font-size:0.9rem; line-height:1.6; color:#fff; background:var(--bg-input); padding:15px; border-radius:12px; border:1px solid #333;">
                    "${bodyText}"
                </div>
            </div>
            
            <!-- Future: Show Lineup / Scorers here -->
            <div style="text-align:center; font-size:0.8rem; color:var(--text-muted);">
                تم التوثيق رسمياً في سجلات المنطقة.
            </div>
        `;
    }

    /**
     * TAB 2: Create Match Form
     */
    async renderCreateForm() {
        const container = document.getElementById('arena-content');
        container.innerHTML = '<div class="loader-bar" style="margin:20px auto"></div>';
        
        try {
            const user = state.getUser();
            const [opponents, venues] = await Promise.all([
                this.matchService.getOpponents(user.zoneId, this.myTeamData.id),
                this.matchService.getVenues(user.zoneId)
            ]);

            container.innerHTML = `
                <div class="match-form-box fade-in">
                    <h3 style="color:var(--gold-main); text-align:center;">تسجيل صافرة النهاية</h3>
                    <form id="form-match">
                        <div class="form-group">
                            <label>الفريق الخصم</label>
                            <select id="inp-opp" required>
                                <option value="" disabled selected>اختر...</option>
                                ${opponents.map(o => `<option value="${o.id}">${o.name}</option>`).join('')}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>الملعب</label>
                            <select id="inp-venue" required>
                                <option value="" disabled selected>المكان...</option>
                                ${venues.map(v => `<option value="${v.id}">${v.name}</option>`).join('')}
                            </select>
                        </div>
                        <div class="score-inputs">
                            <div class="si-box"><label>نحن</label><input type="number" id="inp-score-my" value="0" min="0"></div>
                            <div class="si-box"><label>هم</label><input type="number" id="inp-score-opp" value="0" min="0"></div>
                        </div>
                        <div class="form-group">
                            <label>التشكيلة الأساسية</label>
                            <div class="roster-grid">
                                ${this.roster.map(p => `<label class="player-chk"><input type="checkbox" name="lineup" value="${p.userId}"><span class="chk-box">${p.name}</span></label>`).join('')}
                            </div>
                        </div>
                        <button type="submit" class="btn-primary" id="btn-submit-match">إرسال النتيجة</button>
                    </form>
                </div>`;
            
            document.getElementById('form-match').addEventListener('submit', (e) => this.handleSubmit(e));
        } catch (e) { container.innerHTML = `<p class="error-text">${e.message}</p>`; }
    }

    /**
     * LOGIC: Submit with Names for Press Engine
     */
    async handleSubmit(e) {
        e.preventDefault();
        const btn = document.getElementById('btn-submit-match');
        btn.disabled = true; btn.textContent = "جاري صياغة الخبر...";
        
        // Get Selected Opponent Name for the News Engine
        const oppSelect = document.getElementById('inp-opp');
        const oppName = oppSelect.options[oppSelect.selectedIndex].text;

        const payload = {
            creatorId: state.getUser().id,
            myTeamId: this.myTeamData.id,
            myTeamName: this.myTeamData.name, // Pass Name
            oppTeamId: oppSelect.value,
            oppTeamName: oppName,             // Pass Name
            venueId: parseInt(document.getElementById('inp-venue').value),
            myScore: parseInt(document.getElementById('inp-score-my').value),
            oppScore: parseInt(document.getElementById('inp-score-opp').value),
            lineup: Array.from(document.querySelectorAll('input[name="lineup"]:checked')).map(cb => cb.value),
            scorers: []
        };

        if (payload.lineup.length < 5) {
            if(!confirm("أقل من 5 لاعبين. متابعة؟")) {
                btn.disabled = false; return;
            }
        }

        try {
            await this.matchService.validateMatchConstraints(payload.myTeamId);
            await this.matchService.submitMatch(payload);
            
            SoundManager.play('success');
            alert("تم تسجيل النتيجة! الخبر الآن قيد المراجعة لدى الكابتن الخصم.");
            this.loadLiveFeed(state.getUser().zoneId);
            
            // Reset Tab
            this.viewContainer.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
            this.viewContainer.querySelector('[data-tab="feed"]').classList.add('active');

        } catch (err) {
            SoundManager.play('error');
            alert("خطأ: " + err.message);
            btn.disabled = false;
            btn.textContent = "إرسال النتيجة";
        }
    }
}
